### ISSUE TITLE
huggingface chat失效了吗？

### ISSUE THREAD

**Issue by foxdodo** [RockChinQ/free-one-api#113]
这个报错什么意思？已经按格式填了huggingface的账号密码
```
024-07-15T19:10:07.810655642Z [2024-07-16 03:10:07.810] /usr/local/lib/python3.10/site-packages/hugchat/hugchat.py (727) - [ERROR] :

2024-07-15T19:10:07.810872021Z No `type` found in response: {'message': 'An error occurred', 'errorId': '129d6973-9a07-4e83-8003-xxxxxx'}

2024-07-15T19:10:07.811143232Z Traceback (most recent call last):

2024-07-15T19:10:07.811202007Z   File "/app/free_one_api/impls/adapter/hugchat.py", line 84, in test

2024-07-15T19:10:07.811234275Z     for data in self.chatbot.query(

2024-07-15T19:10:07.811271781Z   File "/usr/local/lib/python3.10/site-packages/hugchat/message.py", line 154, in __next__

2024-07-15T19:10:07.811314093Z     raise self.error

2024-07-15T19:10:07.811346961Z   File "/usr/local/lib/python3.10/site-packages/hugchat/message.py", line 100, in __next__

2024-07-15T19:10:07.811372762Z     self._filterResponse(a)

2024-07-15T19:10:07.811443488Z   File "/usr/local/lib/python3.10/site-packages/hugchat/message.py", line 84, in _filterResponse

2024-07-15T19:10:07.811475774Z     raise ChatError(f"Server returns an error: {obj['message']}")

2024-07-15T19:10:07.811565193Z hugchat.exceptions.ChatError: Server returns an error: An error occurred

2024-07-15T19:10:07.812841307Z Traceback (most recent call last):

2024-07-15T19:10:07.813034077Z   File "/app/free_one_api/impls/channel/mgr.py", line 114, in test_channel

2024-07-15T19:10:07.813078087Z     raise ValueError(error)

2024-07-15T19:10:07.813287627Z ValueError: Server returns an error: An error occurred

2024-07-15T19:10:07.813386714Z 

2024-07-15T19:10:07.813412323Z The above exception was the direct cause of the following exception:

2024-07-15T19:10:07.813439253Z 

2024-07-15T19:10:07.813532468Z Traceback (most recent call last):

2024-07-15T19:10:07.813634058Z   File "/app/free_one_api/impls/router/api.py", line 147, in channel_test

2024-07-15T19:10:07.813667724Z     latency = await self.chanmgr.test_channel(chan_id)

2024-07-15T19:10:07.813756570Z   File "/app/free_one_api/impls/channel/mgr.py", line 117, in test_channel

2024-07-15T19:10:07.813790169Z     raise ValueError("Test failed.") from e

2024-07-15T19:10:07.813867164Z ValueError: Test failed.
```

**Comment by MrWoods1692** [comment]
修复了，你看看。[Commit c3824a1](https://github.com/RockChinQ/free-one-api/commit/c3824a1e98a35d8a32cc2b5d143b9b2982694813)
